library(readxl)
data = read_excel("crypt.xlsx")
str(data)
unique(data$Type)
data$Date = as.Date(data$Date,format = "%b %d,%Y")
data$Volume = as.factor(data$Volume)
data$Volume = as.numeric(data$Volume)
data$`Market Cap` = as.factor(data$`Market Cap`)
data$`Market Cap` = as.numeric(data$`Market Cap`)
data$Open = round(data$Open)
data$High = round(data$High)
data$Low = round(data$Low)
data$Close = round(data$Close)
data$Type = factor(data$Type,levels = unique(data$Type),labels = unique(data$Type))
str(data)

write.csv(data,"D://dv assignment 3//currency.csv")
